site_name: pyWC Documentation
site_description: High-performance Willard-Chandler surface analysis toolkit for molecular dynamics
site_author: Massimo Marchi
site_url: https://octupole.github.io/pyWC

repo_name: octupole/pyWC
repo_url: https://github.com/octupole/pyWC
edit_uri: edit/main/docs/

copyright: |
  Copyright &copy; 2025 Massimo Marchi<br>
  Original pytim by Marcello Sega et al. (2018)<br>
  Licensed under GPL-3.0

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  font:
    text: Roboto
    code: Roboto Mono

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/octupole/pyWC
    - icon: fontawesome/solid/envelope
      link: mailto:massimo@octupole.org

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - CLI Tools: cli-tools.md
    - Examples: examples.md
  - API Reference:
    - WillardChandler: api/willard_chandler.md
    - Backends: api/backends.md
  - Community:
    - Citation: citation.md
    - Contributing: contributing.md
  - External Links:
    - GitHub Repository: https://github.com/octupole/pyWC
    - Report Issues: https://github.com/octupole/pyWC/issues
    - Original pytim: https://github.com/Marcello-Sega/pytim

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
